version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: schnauzdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: